import { useWallet } from '@solana/wallet-adapter-react';
import type { NextPage } from 'next'
import Head from 'next/head';
import { useState } from 'react';
import { Toaster } from 'react-hot-toast';
import ChatList from '../components/ChatComponents/ChatList';
import ChatMessages from '../components/ChatComponents/ChatMessages';
import LoadingSpinner from '../components/UtilityComponents/LoadingSpinner';

const Messages: NextPage = () => {

  const { publicKey, connected } = useWallet();

  if (!publicKey){
    return(
        <div className="flex flex-col w-screen h-screen items-center justify-center bg-gray-600 space-y-6 pl-16 ">
          
          <p className='md:text-2xl text-md text-teal-400 font-bold font-mono'>
            Please connect your wallet
          </p>
          <LoadingSpinner sizeOf ={'large'}></LoadingSpinner>
        </div>
    )
  }

  return (
    <>
    <Head>
      <title>Zelda</title>
      <link rel='icon' href="https://icon-library.com/images/mms-icon/mms-icon-17.jpg"/>
      <meta name="description" content="Generated by create next app" />
    </Head>              
    <div className='pl-16 pt-16'>
      <Toaster/>
      <div className="absolute z-30">
        <ChatList/>
      </div>

      <div className='w-full h-full z-10'>
          <ChatMessages/>
      </div>

    </div>
     </>
  );
}

export default Messages
